version: "3.7"

services:
  mini-autorizador:
    build: ./
    container_name: "miniautorizador"
    ports:
      - 8080:8080
  
  mongo:
    image: mongo:4.2
    hostname: mongo
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: miniautorizador
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./scripts/init.js:/docker-entrypoint-initdb.d/init.js:ro

#
#ADICIONEI O MONGO-EXPRESS, POIS VIABLIZA UMA FORMA SIMPLES PARA GERIR OS DADOS DAS COLLECTIONS ATRAVES DO ENDPOINT http://localhost:8081
#
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: password
    ports:
      - "8081:8081"
    depends_on:
      - mongo

#  mysql:
#    image: mysql:5.7
#    hostname: mysql
#    container_name: mysql
#    restart: always
#    ports:
#     - "3306:3306"
#    environment:
#      MYSQL_DATABASE: miniautorizador
#      MYSQL_ROOT_PASSWORD:
#      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"